import Head from 'next/head'
import { useRouter } from 'next/router'
import { Col, Container, Navbar } from 'react-bootstrap'
import AtomoItem from '../components/atomo_item/atomo_item'
import GridContainer from '../components/grid_container'
import { Elemento } from '../domain/entities/elemento'

function Home({ elements }: any) {

  const router = useRouter()

  const goToDetails = (elemento: Elemento) => {
    router.push(`/atomo/details?id=${elemento.symbol}`)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar bg="dark" variant="dark">
          <Container>
            <Navbar.Brand href="">
              Tabela periodica ONLINE
            </Navbar.Brand>
          </Container>
        </Navbar>

        <GridContainer>
          {elements && elements.map((e: any) =>
            <AtomoItem
              key={e.symbol}
              elemento={e}
              background_color={e['cpk-hex']!}
              onClick={goToDetails} />)}
        </GridContainer>

      </main>

    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/hello')
  const elements = await res.json()

  return {
    props: {
      elements: elements.data.elements,
    },
  }
}

export default Home
